version: "3.8"

services:
  postgres_db:
    image: postgres:13-alpine
    volumes:
      - ./script/pg_db_init.sql:/docker-entrypoint-initdb.d/pg_db_init.sql
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  pyspark:
    build:
      context: .
      dockerfile: Dockerfile.pyspark
    volumes:
      - ./pyspark/:/opt/pyspark_app/
      - ./resources/jars:/opt/pyspark_app/jars/
    command: "schema_evolution_with_apache_iceberg.py"
    depends_on:
      - postgres_db
    ports:
      - 4040:4040

volumes:
  postgres_data:
